#!/bin/bash
#
# list words in a file with a uniqness count to identify typing mistakes.
# Usage: ./uniquewordcount MyFile | more
#        ./uniquewordcount < MyFile > UniqueWordsWithCount
#
(echo "$1"; cat) | tr -cs "[:alpha:]" "\n" | sort | uniq -c
